[package]
name = "blades"
version = "0.1.2"
authors = ["Maroš Grego <maros@grego.site>"]
edition = "2018"
description = "Blazing fast dead simple static site generator"
repository = "https://github.com/grego/blades"
keywords = ["website", "site", "generator"]
categories = ["command-line-utilities", "web-programming"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://www.getblades.org"

[dependencies]
toml = "0.5.7"
ramhorns = "0.10.1"
beef = { version = "0.5.0", features = ["impl_serde"]}
serde = { version = "1.0.116", features = ["derive"] }
custom_error = "1.8.0"
chrono = {version = "0.4.19", features = ["serde"] }
ahash = "0.5.1"
parking_lot = "0.11"
rayon = "1.4.1"
structopt = "0.3.20"

[profile.release]
lto = true

[profile.bench]
lto = true
